---

- hosts: rhel
  become: yes


  tasks:
    - name: Delete target kernel
      yum:
        name: kernel-3.10.0-1160.31.1.el7.x86_64
        state: absent
      when: ansible_distribution_major_version == "7"  