---

- name: Server Log Files Cleanup
  hosts: localhost
  gather_facts: no
  become: yes
  
  tasks:
   - name: Look for Files
     find:
       paths: "{{ item }}"    
       age: 90d
       patterns: 'file*.txt,arch*.txt'
     with_items:
       - /home/jeivier/test1/testfiles
       - /home/jeivier/test2/testfiles
     register: files_to_delete

   - set_fact: 
       pathlist={{ files_to_delete.results | map(attribute="files") | list }}  
       
   - debug:
       msg: '{{ pathlist | map(attribute="path") | list }}'

#   - name: Delete files 
#     file:
#       path: "{{ item }}"
#       state: absent
#     with_items: '{{ }}'     
