--- #Patch Linux Machines running Debian based distributions

- hosts: debian
  become: yes
  tasks:
    - name: "Update Repo Cache"
      apt:
        update_cache: yes
    - name: "Upgrade Packages"
      apt:
        upgrade: yes
    - name: "Update Last Patch File"
      file:
        path: /etc/last_patched
        state: touch    